// N64Z80 testsuite ROM. Everything prints through ISViewer (debugf); every
// verdict line starts with ">>> PASS" or ">>> FAIL", and the run ends with
// the done marker (tools/ares-run.ps1 stops ares when it sees it).
//
// M0: the "candidate" core is still the reference (NEW = an unmodified copy),
// so this validates the harness itself: C vs C must be clean and every
// planted-bug mutant must be caught.
#include <libdragon.h>
#include <string.h>
#include "zdiff.h"
#include "zex.h"
#include "bench.h"
#include "tlog.h"
#include "zex_expect.h"
#include "test_config.h"   // generated by the Makefile from its test knobs

#ifndef ZDIFF_CASES
#define ZDIFF_CASES 20000
#endif
#ifndef ZDIFF_SEED
#define ZDIFF_SEED 1
#endif
// ZEXDOC groups whose instruction count (zex_expect.h) is at most this run in
// the normal loop; 0 runs all 67 (about 5.8G instructions: hours).
#ifndef ZEX_MAX_STEPS
#define ZEX_MAX_STEPS 5000000
#endif

#define DONE_MARKER "*** N64Z80 TESTSUITE DONE ***"

// z80.c's z80_init references mvs64's dcache alignment marker on N64.
const uint8_t z80_rodata_anchor[1] = { 0 };

extern const uint8_t zex_prelim[], zex_prelim_end[];
extern const uint8_t zex_zexdoc[], zex_zexdoc_end[];

static int failures;

static void verdict(int ok, const char* fmt, const char* what, long a, long b) {
  char msg[160];
  snprintf(msg, sizeof msg, fmt, what, a, b);
  tlog(">>> %s %s\n", ok ? "PASS" : "FAIL", msg);
  failures += !ok;
}

static void run_zdiff(void) {
  zdiff_cfg cfg = { .cases = ZDIFF_CASES, .seed = ZDIFF_SEED, .max_report = 4 };
  uint32_t t0 = TICKS_READ();
  long bad = zdiff(&REF_core, &NEW_core, &cfg);
  uint32_t ms = TICKS_TO_MS(TICKS_SINCE(t0));
  verdict(bad == 0, "zdiff %s: %ld cases, %ld mismatches", "REF vs NEW", cfg.cases, bad);
  tlog("    (%lu ms, %lu cases/s)\n", (unsigned long)ms, (unsigned long)(ms ? cfg.cases * 1000 / ms : 0));

  cfg.direct = 1;
  cfg.cases = ZDIFF_CASES / 4;
  bad = zdiff(&REF_core, &NEW_core, &cfg);
  verdict(bad == 0, "zdiff %s: %ld cases, %ld mismatches", "REF vs NEW (direct-write filter)", cfg.cases, bad);

  // Negative controls: each planted bug must produce mismatches.
  const zcore* mut[] = { &MUT1_core, &MUT2_core, &MUT3_core, &MUT4_core };
  cfg.direct = 0;
  cfg.cases = ZDIFF_CASES;
  cfg.max_report = 0;
  for (int i = 0; i < 4; i++) {
    bad = zdiff(&REF_core, mut[i], &cfg);
    verdict(bad > 0, "zdiff control %s: %ld mismatches in %ld cases (must be > 0)", mut[i]->name, bad, cfg.cases);
  }
}

static void run_zex(const zcore* core) {
  size_t len = zex_prelim_end - zex_prelim;
  zex_result r = zex_run(core, zex_prelim, len, -1, 0, 0);
  int ok = r.complete == 1 && !r.err && r.steps == 899 && r.cycles == 8721;
  verdict(ok, "prelim on %s: %ld instructions, %ld cycles (expect 899, 8721)", core->name,
          (long)r.steps, (long)r.cycles);

  len = zex_zexdoc_end - zex_zexdoc;
  int groups = zex_groups(zex_zexdoc, len), ran = 0, passed = 0;
  uint64_t steps = 0, ticks = 0;
  for (int g = 0; g < groups; g++) {
    const zex_expect* e = &zexdoc_expect[g];
    if (ZEX_MAX_STEPS && e->steps > ZEX_MAX_STEPS) continue;
    r = zex_run(core, zex_zexdoc, len, g, 0, 1);
    ok = r.ok == 1 && !r.err && r.complete == 1 && r.steps == e->steps && r.cycles == e->cycles;
    if (!ok)
      tlog("    zexdoc %2d %s: ok=%d err=%d steps %llu/%llu cycles %llu/%llu\n", g,
           zex_group_name(zex_zexdoc, len, g), r.ok, r.err, (unsigned long long)r.steps,
           (unsigned long long)e->steps, (unsigned long long)r.cycles, (unsigned long long)e->cycles);
    ran++; passed += ok;
    steps += r.steps; ticks += r.ticks;
  }
  char what[48];
  snprintf(what, sizeof what, "zexdoc on %s", core->name);
  verdict(passed == ran, "%s: %ld/%ld groups exact (steps, cycles, CRC)", what, passed, ran);
  if (steps)
    tlog("[BENCH] %s zexdoc subset: %lu ns/instr  (%llu instr, %lu ms)\n", core->name,
         (unsigned long)(ticks * 1000000000ull / TICKS_PER_SECOND / steps), (unsigned long long)steps,
         (unsigned long)(ticks / (TICKS_PER_SECOND / 1000)));
}

int main(void) {
  debug_init_isviewer();
  debug_init_usblog();
  tlog("\nN64Z80 testsuite (M0: reference vs reference)\n");
  tlog("config: ZDIFF_CASES=%d ZDIFF_SEED=%d ZEX_MAX_STEPS=%d\n", ZDIFF_CASES, ZDIFF_SEED, ZEX_MAX_STEPS);

  run_zdiff();
  bench_core(&REF_core);
  bench_window_copy();
  run_zex(&NEW_core);

  tlog(">>> SUMMARY %s: %d failure(s)\n", failures ? "FAIL" : "PASS", failures);
  tlog("%s\n", DONE_MARKER);
  // ares block-buffers its stdout: push the marker out with padding.
  for (int i = 0; i < 80; i++)
    tlog("................................................................................................................................................................................................................................\n");
  for (;;) {}
}
