// N64Z80 testsuite ROM. Everything prints through ISViewer (debugf); every
// verdict line starts with ">>> PASS" or ">>> FAIL", and the run ends with
// the done marker (tools/ares-run.ps1 stops ares when it sees it).
//
// The candidate is the asm core (ASM, n64z80.h). M1: its run loop is asm and
// every instruction still executes in the C fallback. The planted-bug
// mutants must still be caught (the harness still checks something).
#include <libdragon.h>
#include <string.h>
#include "zdiff.h"
#include "zex.h"
#include "replay.h"
#include "bench.h"
#include "tlog.h"
#include "zex_expect.h"
#include "test_config.h"   // generated by the Makefile from its test knobs

#ifndef ZDIFF_CASES
#define ZDIFF_CASES 20000
#endif
#ifndef ZDIFF_SEED
#define ZDIFF_SEED 1
#endif
// ZEXDOC groups whose instruction count (zex_expect.h) is at most this run in
// the normal loop; 0 runs all 67 (about 5.8G instructions: hours).
#ifndef ZEX_MAX_STEPS
#define ZEX_MAX_STEPS 5000000
#endif

#define DONE_MARKER "*** N64Z80 TESTSUITE DONE ***"

// z80.c's z80_init references mvs64's dcache alignment marker on N64.
const uint8_t z80_rodata_anchor[1] = { 0 };

extern const uint8_t zex_prelim[], zex_prelim_end[];
extern const uint8_t zex_zexdoc[], zex_zexdoc_end[];
extern const uint8_t zex_zexall[], zex_zexall_end[];

// n64z80.c: fallback entries whose asm fetch pointer disagreed with the rmap.
extern uint32_t n64z80_fetch_mismatch;

static int failures;

static void verdict(int ok, const char* fmt, const char* what, long a, long b) {
  char msg[160];
  snprintf(msg, sizeof msg, fmt, what, a, b);
  tlog(">>> %s %s\n", ok ? "PASS" : "FAIL", msg);
  failures += !ok;
}

static void run_zdiff(void) {
  zdiff_cfg cfg = { .cases = ZDIFF_CASES, .seed = ZDIFF_SEED, .max_report = 4 };
  uint32_t t0 = TICKS_READ();
  long bad = zdiff(&REF_core, &ASM_core, &cfg);
  uint32_t ms = TICKS_TO_MS(TICKS_SINCE(t0));
  verdict(bad == 0, "zdiff %s: %ld cases, %ld mismatches", "REF vs ASM", cfg.cases, bad);
  tlog("    (%lu ms, %lu cases/s)\n", (unsigned long)ms, (unsigned long)(ms ? cfg.cases * 1000 / ms : 0));

  cfg.direct = 1;
  cfg.cases = ZDIFF_CASES / 4;
  bad = zdiff(&REF_core, &ASM_core, &cfg);
  verdict(bad == 0, "zdiff %s: %ld cases, %ld mismatches", "REF vs ASM (direct-write filter)", cfg.cases, bad);

  // Negative controls: each planted bug must produce mismatches.
  const zcore* mut[] = { &MUT1_core, &MUT2_core, &MUT3_core, &MUT4_core };
  cfg.direct = 0;
  cfg.cases = ZDIFF_CASES;
  cfg.max_report = 0;
  for (int i = 0; i < 4; i++) {
    bad = zdiff(&REF_core, mut[i], &cfg);
    verdict(bad > 0, "zdiff control %s: %ld mismatches in %ld cases (must be > 0)", mut[i]->name, bad, cfg.cases);
  }
}

// Every group of `img` with at most ZEX_MAX_STEPS instructions, each run
// alone through z80_run and checked against the reference's exact
// instruction and cycle counts in that mode (zex_expect.h).
static void run_zex_groups(const zcore* core, const char* name, const uint8_t* img, size_t len,
                           const zex_expect* expect) {
  int groups = zex_groups(img, len), ran = 0, passed = 0;
  uint64_t steps = 0, ticks = 0;
  for (int g = 0; g < groups; g++) {
    const zex_expect* e = &expect[g];
    if (ZEX_MAX_STEPS && e->run_steps > ZEX_MAX_STEPS) continue;
    zex_result r = zex_run(core, img, len, g, 1, 1);
    int ok = r.ok == 1 && !r.err && r.complete == 1 && r.steps == e->run_steps &&
             r.cycles == e->run_cycles;
    if (!ok)
      tlog("    %s %2d %s: ok=%d err=%d steps %llu/%llu cycles %llu/%llu\n", name, g,
           zex_group_name(img, len, g), r.ok, r.err, (unsigned long long)r.steps,
           (unsigned long long)e->run_steps, (unsigned long long)r.cycles,
           (unsigned long long)e->run_cycles);
    ran++; passed += ok;
    steps += r.steps; ticks += r.ticks;
  }
  char what[48];
  snprintf(what, sizeof what, "%s on %s", name, core->name);
  verdict(passed == ran, "%s: %ld/%ld groups exact through z80_run (steps, cycles, CRC)", what,
          passed, ran);
  if (steps)
    tlog("[BENCH] %s %s subset: %lu ns/instr  (%llu instr, %lu ms)\n", core->name, name,
         (unsigned long)(ticks * 1000000000ull / TICKS_PER_SECOND / steps), (unsigned long long)steps,
         (unsigned long)(ticks / (TICKS_PER_SECOND / 1000)));
}

static void run_zex(const zcore* core) {
  zex_result r = zex_run(core, zex_prelim, zex_prelim_end - zex_prelim, -1, 1, 0);
  int ok = r.complete == 1 && !r.err && r.steps == 904 && r.cycles == 8754;
  verdict(ok, "prelim on %s: %ld instructions, %ld cycles through z80_run (expect 904, 8754)",
          core->name, (long)r.steps, (long)r.cycles);
  run_zex_groups(core, "zexdoc", zex_zexdoc, zex_zexdoc_end - zex_zexdoc, zexdoc_expect);
  run_zex_groups(core, "zexall", zex_zexall, zex_zexall_end - zex_zexall, zexall_expect);
}

static int ends_with(const char* s, const char* suf) {
  size_t a = strlen(s), b = strlen(suf);
  return a >= b && !strcmp(s + a - b, suf);
}

// Replays every mvs64 owner trace in the ROM filesystem (test/traces/*.z80t,
// packed by the Makefile when present): REF gives the baseline speed on real
// driver code, ASM must replay clean, MUT1 must be caught.
static void run_traces(void) {
  char names[8][64];
  int n = 0;
  dir_t d;
  if (dir_findfirst("rom:/", &d) == 0) {
    do {
      if (d.d_type == DT_REG && ends_with(d.d_name, ".z80t") && n < 8)
        snprintf(names[n++], sizeof names[0], "%s", d.d_name);
    } while (dir_findnext("rom:/", &d) == 0);
  }
  if (!n) { tlog("(no traces in the ROM: copy mvs64 *.z80t files to test/traces/)\n"); return; }
  for (int i = 0; i < n; i++) {
    char path[80];
    snprintf(path, sizeof path, "rom:/%.63s", names[i]);
    FILE* f = fopen(path, "rb");
    if (!f) { verdict(0, "trace %.63s: cannot open (%ld, %ld)", names[i], 0, 0); continue; }
    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    fseek(f, 0, SEEK_SET);
    uint8_t* tr = malloc(len);
    if (!tr || fread(tr, 1, len, f) != (size_t)len) {
      fclose(f); free(tr);
      verdict(0, "trace %.63s: cannot load %ld bytes (%ld)", names[i], len, 0);
      continue;
    }
    fclose(f);
    const zcore* cores[] = { &REF_core, &ASM_core, &MUT1_core };
    for (int c = 0; c < 3; c++) {
      replay_result r = replay(cores[c], tr, len, c < 2 ? 4 : 0);
      char what[96];
      snprintf(what, sizeof what, "replay %.63s on %.15s", names[i], cores[c]->name);
      if (c < 2)
        verdict(r.ended && !r.bad, "%s: %ld instr, %ld mismatches", what, r.steps, r.bad);
      else
        verdict(r.bad || !r.ended, "%s: %ld mismatches, control (must be > 0)", what, r.bad, 0);
      if (c < 2 && r.steps)
        tlog("[BENCH] %s trace %-20s %5lu ns/instr  %4lu cycles/instr  (%ld instr, %ld runs)\n",
             cores[c]->name, names[i],
             (unsigned long)(r.ticks * 1000000000ull / TICKS_PER_SECOND / r.steps),
             (unsigned long)(r.ticks * 2 / r.steps), r.steps, r.runs);
    }
    free(tr);
  }
}

int main(void) {
  debug_init_isviewer();
  debug_init_usblog();
  dfs_init(DFS_DEFAULT_LOCATION);
  tlog("\nN64Z80 testsuite (M1: asm run loop, C fallback for every opcode)\n");
  tlog("config: ZDIFF_CASES=%d ZDIFF_SEED=%d ZEX_MAX_STEPS=%d\n", ZDIFF_CASES, ZDIFF_SEED, ZEX_MAX_STEPS);

  run_zdiff();
  run_traces();
  bench_core(&REF_core);
  bench_core(&ASM_core);
  bench_window_copy();
  run_zex(&ASM_core);
  verdict(n64z80_fetch_mismatch == 0, "%s: %ld fetch pointer mismatches (%ld)", "ASM rmap mapping",
          (long)n64z80_fetch_mismatch, 0);

  tlog(">>> SUMMARY %s: %d failure(s)\n", failures ? "FAIL" : "PASS", failures);
  tlog("%s\n", DONE_MARKER);
  // ares block-buffers its stdout: push the marker out with padding.
  for (int i = 0; i < 80; i++)
    tlog("................................................................................................................................................................................................................................\n");
  for (;;) {}
}
