// Generated by test/pc (zpc expect): per-group results of the reference
// core, each group run alone, driven by z80_step and by z80_run (whose
// stop points overshoot the final OUT differently). Do not edit.
typedef struct {
  uint64_t steps, cycles; int pass;
  uint64_t run_steps, run_cycles;
} zex_expect;
static const zex_expect zexdoc_expect[67] = {
  {  279550747ull,   2260470243ull, 1,  279550752ull,   2260470276ull }, //  0 <adc,sbc> hl,<bc,de,hl,sp>
  {  139195717ull,   1124958651ull, 1,  139195722ull,   1124958684ull }, //  1 add hl,<bc,de,hl,sp>
  {  139232069ull,   1125685691ull, 1,  139232074ull,   1125685724ull }, //  2 add ix,<bc,de,ix,sp>
  {  139232069ull,   1125685691ull, 1,  139232074ull,   1125685724ull }, //  3 add iy,<bc,de,iy,sp>
  {   70532174ull,    574692437ull, 1,   70532179ull,    574692470ull }, //  4 aluop a,nn
  { 2461064646ull,  20006915235ull, 1, 2461064651ull,  20006915268ull }, //  5 aluop a,<b,c,d,e,h,l,(hl),a>
  { 1255945312ull,  10169844747ull, 1, 1255945317ull,  10169844780ull }, //  6 aluop a,<ixh,ixl,iyh,iyl>
  {  637477420ull,   5122999153ull, 1,  637477425ull,   5122999186ull }, //  7 aluop a,(<ix,iy>+1)
  {    4955376ull,     40245705ull, 1,    4955381ull,     40245738ull }, //  8 bit n,(<ix,iy>+1)
  {  158658904ull,   1290420306ull, 1,  158658909ull,   1290420339ull }, //  9 bit n,<b,c,d,e,h,l,(hl),a>
  {   31068010ull,    252185444ull, 1,   31068015ull,    252185477ull }, // 10 cpd<r>
  {   31085433ull,    252551327ull, 1,   31085438ull,    252551360ull }, // 11 cpi<r>
  {  136056626ull,   1108961370ull, 1,  136056631ull,   1108961403ull }, // 12 <daa,cpl,scf,ccf>
  {    7352143ull,     59892057ull, 1,    7352148ull,     59892090ull }, // 13 <inc,dec> a
  {    7352143ull,     59892057ull, 1,    7352148ull,     59892090ull }, // 14 <inc,dec> b
  {    3793624ull,     30695186ull, 1,    3793629ull,     30695219ull }, // 15 <inc,dec> bc
  {    7352143ull,     59892057ull, 1,    7352148ull,     59892090ull }, // 16 <inc,dec> c
  {    7352143ull,     59892057ull, 1,    7352148ull,     59892090ull }, // 17 <inc,dec> d
  {    3793624ull,     30695186ull, 1,    3793629ull,     30695219ull }, // 18 <inc,dec> de
  {    7352143ull,     59892057ull, 1,    7352148ull,     59892090ull }, // 19 <inc,dec> e
  {    7352143ull,     59892057ull, 1,    7352148ull,     59892090ull }, // 20 <inc,dec> h
  {    3793624ull,     30695186ull, 1,    3793629ull,     30695219ull }, // 21 <inc,dec> hl
  {    3795416ull,     30731026ull, 1,    3795421ull,     30731059ull }, // 22 <inc,dec> ix
  {    3795416ull,     30731026ull, 1,    3795421ull,     30731059ull }, // 23 <inc,dec> iy
  {    7352143ull,     59892057ull, 1,    7352148ull,     59892090ull }, // 24 <inc,dec> l
  {    7352143ull,     59917145ull, 1,    7352148ull,     59917178ull }, // 25 <inc,dec> (hl)
  {    3793624ull,     30695186ull, 1,    3793629ull,     30695219ull }, // 26 <inc,dec> sp
  {   15411539ull,    125034707ull, 1,   15411544ull,    125034740ull }, // 27 <inc,dec> (<ix,iy>+1)
  {    7355727ull,     59963737ull, 1,    7355732ull,     59963770ull }, // 28 <inc,dec> ixh
  {    7355727ull,     59963737ull, 1,    7355732ull,     59963770ull }, // 29 <inc,dec> ixl
  {    7355727ull,     59963737ull, 1,    7355732ull,     59963770ull }, // 30 <inc,dec> iyh
  {    7355727ull,     59963737ull, 1,    7355732ull,     59963770ull }, // 31 <inc,dec> iyl
  {      73073ull,       593081ull, 1,      73078ull,       593114ull }, // 32 ld <bc,de>,(nnnn)
  {      36245ull,       293157ull, 1,      36250ull,       293190ull }, // 33 ld hl,(nnnn)
  {      36228ull,       293157ull, 1,      36233ull,       293190ull }, // 34 ld sp,(nnnn)
  {      73141ull,       593761ull, 1,      73146ull,       593794ull }, // 35 ld <ix,iy>,(nnnn)
  {     167691ull,      1363885ull, 1,     167696ull,      1363918ull }, // 36 ld (nnnn),<bc,de>
  {      36245ull,       293157ull, 1,      36250ull,       293190ull }, // 37 ld (nnnn),hl
  {      36228ull,       293157ull, 1,      36233ull,       293190ull }, // 38 ld (nnnn),sp
  {     167823ull,      1365205ull, 1,     167828ull,      1365238ull }, // 39 ld (nnnn),<ix,iy>
  {     144797ull,      1179730ull, 1,     144802ull,      1179763ull }, // 40 ld <bc,de,hl,sp>,nnnn
  {      73141ull,       593557ull, 1,      73146ull,       593590ull }, // 41 ld <ix,iy>,nnnn
  {     106316ull,       861298ull, 1,     106321ull,       861331ull }, // 42 ld a,<(bc),(de)>
  {     139116ull,      1135151ull, 1,     139121ull,      1135184ull }, // 43 ld <b,c,d,e,h,l,(hl),a>,nn
  {      73141ull,       593727ull, 1,      73146ull,       593760ull }, // 44 ld (<ix,iy>+1),nn
  {    1302907ull,     10489926ull, 1,    1302912ull,     10489959ull }, // 45 ld <b,c,d,e>,(<ix,iy>+1)
  {     647975ull,      5212332ull, 1,     647980ull,      5212365ull }, // 46 ld <h,l>,(<ix,iy>+1)
  {     311757ull,      2518052ull, 1,     311762ull,      2518085ull }, // 47 ld a,(<ix,iy>+1)
  {      73102ull,       590264ull, 1,      73107ull,       590297ull }, // 48 ld <ixh,ixl,iyh,iyl>,nn
  {   11166226ull,     90862646ull, 1,   11166231ull,     90862679ull }, // 49 ld <bcdehla>,<bcdehla>
  {   23031924ull,    186806071ull, 1,   23031929ull,    186806104ull }, // 50 ld <bcdexya>,<bcdexya>
  {     106224ull,       861206ull, 1,     106229ull,       861239ull }, // 51 ld a,(nnnn) / ld (nnnn),a
  {     106270ull,       861528ull, 1,     106275ull,       861561ull }, // 52 ldd<r> (1)
  {     106293ull,       862011ull, 1,     106298ull,       862044ull }, // 53 ldd<r> (2)
  {     106270ull,       861528ull, 1,     106275ull,       861561ull }, // 54 ldi<r> (1)
  {     106293ull,       862011ull, 1,     106298ull,       862044ull }, // 55 ldi<r> (2)
  {   32049776ull,    262717745ull, 1,   32049781ull,    262717778ull }, // 56 neg
  {   17373680ull,    141533239ull, 1,   17373685ull,    141533272ull }, // 57 <rrd,rld>
  {   14823845ull,    120813313ull, 1,   14823850ull,    120813346ull }, // 58 <rlca,rrca,rla,rra>
  {    1013379ull,      8186209ull, 1,    1013384ull,      8186242ull }, // 59 shf/rot (<ix,iy>+1)
  {   22598372ull,    183148570ull, 1,   22598377ull,    183148603ull }, // 60 shf/rot <b,c,d,e,h,l,(hl),a>
  {   22552296ull,    183598039ull, 1,   22552301ull,    183598072ull }, // 61 <set,res> n,<bcdehl(hl)a>
  {    1054025ull,      8570023ull, 1,    1054030ull,      8570056ull }, // 62 <set,res> n,(<ix,iy>+1)
  {    2975109ull,     23961558ull, 1,    2975114ull,     23961591ull }, // 63 ld (<ix,iy>+1),<b,c,d,e>
  {     647975ull,      5212332ull, 1,     647980ull,      5212365ull }, // 64 ld (<ix,iy>+1),<h,l>
  {     150832ull,      1216376ull, 1,     150837ull,      1216409ull }, // 65 ld (<ix,iy>+1),a
  {     233250ull,      1899702ull, 1,     233255ull,      1899735ull }, // 66 ld (<bc,de>),a
};
static const zex_expect zexall_expect[67] = {
  {  279550747ull,   2260470243ull, 1,  279550752ull,   2260470276ull }, //  0 <adc,sbc> hl,<bc,de,hl,sp>
  {  139195717ull,   1124958651ull, 1,  139195722ull,   1124958684ull }, //  1 add hl,<bc,de,hl,sp>
  {  139232069ull,   1125685691ull, 1,  139232074ull,   1125685724ull }, //  2 add ix,<bc,de,ix,sp>
  {  139232069ull,   1125685691ull, 1,  139232074ull,   1125685724ull }, //  3 add iy,<bc,de,iy,sp>
  {   70532174ull,    574692437ull, 1,   70532179ull,    574692470ull }, //  4 aluop a,nn
  { 2461064646ull,  20006915235ull, 1, 2461064651ull,  20006915268ull }, //  5 aluop a,<b,c,d,e,h,l,(hl),a>
  { 1255945312ull,  10169844747ull, 1, 1255945317ull,  10169844780ull }, //  6 aluop a,<ixh,ixl,iyh,iyl>
  {  637477420ull,   5122999153ull, 1,  637477425ull,   5122999186ull }, //  7 aluop a,(<ix,iy>+1)
  {    4955376ull,     40245705ull, 1,    4955381ull,     40245738ull }, //  8 bit n,(<ix,iy>+1)
  {  158658904ull,   1290420306ull, 1,  158658909ull,   1290420339ull }, //  9 bit n,<b,c,d,e,h,l,(hl),a>
  {   31068010ull,    252185444ull, 1,   31068015ull,    252185477ull }, // 10 cpd<r>
  {   31085433ull,    252551327ull, 1,   31085438ull,    252551360ull }, // 11 cpi<r>
  {  136056626ull,   1108961370ull, 1,  136056631ull,   1108961403ull }, // 12 <daa,cpl,scf,ccf>
  {    7352143ull,     59892057ull, 1,    7352148ull,     59892090ull }, // 13 <inc,dec> a
  {    7352143ull,     59892057ull, 1,    7352148ull,     59892090ull }, // 14 <inc,dec> b
  {    3793624ull,     30695186ull, 1,    3793629ull,     30695219ull }, // 15 <inc,dec> bc
  {    7352143ull,     59892057ull, 1,    7352148ull,     59892090ull }, // 16 <inc,dec> c
  {    7352143ull,     59892057ull, 1,    7352148ull,     59892090ull }, // 17 <inc,dec> d
  {    3793624ull,     30695186ull, 1,    3793629ull,     30695219ull }, // 18 <inc,dec> de
  {    7352143ull,     59892057ull, 1,    7352148ull,     59892090ull }, // 19 <inc,dec> e
  {    7352143ull,     59892057ull, 1,    7352148ull,     59892090ull }, // 20 <inc,dec> h
  {    3793624ull,     30695186ull, 1,    3793629ull,     30695219ull }, // 21 <inc,dec> hl
  {    3795416ull,     30731026ull, 1,    3795421ull,     30731059ull }, // 22 <inc,dec> ix
  {    3795416ull,     30731026ull, 1,    3795421ull,     30731059ull }, // 23 <inc,dec> iy
  {    7352143ull,     59892057ull, 1,    7352148ull,     59892090ull }, // 24 <inc,dec> l
  {    7352143ull,     59917145ull, 1,    7352148ull,     59917178ull }, // 25 <inc,dec> (hl)
  {    3793624ull,     30695186ull, 1,    3793629ull,     30695219ull }, // 26 <inc,dec> sp
  {   15411539ull,    125034707ull, 1,   15411544ull,    125034740ull }, // 27 <inc,dec> (<ix,iy>+1)
  {    7355727ull,     59963737ull, 1,    7355732ull,     59963770ull }, // 28 <inc,dec> ixh
  {    7355727ull,     59963737ull, 1,    7355732ull,     59963770ull }, // 29 <inc,dec> ixl
  {    7355727ull,     59963737ull, 1,    7355732ull,     59963770ull }, // 30 <inc,dec> iyh
  {    7355727ull,     59963737ull, 1,    7355732ull,     59963770ull }, // 31 <inc,dec> iyl
  {      73073ull,       593081ull, 1,      73078ull,       593114ull }, // 32 ld <bc,de>,(nnnn)
  {      36245ull,       293157ull, 1,      36250ull,       293190ull }, // 33 ld hl,(nnnn)
  {      36228ull,       293157ull, 1,      36233ull,       293190ull }, // 34 ld sp,(nnnn)
  {      73141ull,       593761ull, 1,      73146ull,       593794ull }, // 35 ld <ix,iy>,(nnnn)
  {     167691ull,      1363885ull, 1,     167696ull,      1363918ull }, // 36 ld (nnnn),<bc,de>
  {      36245ull,       293157ull, 1,      36250ull,       293190ull }, // 37 ld (nnnn),hl
  {      36228ull,       293157ull, 1,      36233ull,       293190ull }, // 38 ld (nnnn),sp
  {     167823ull,      1365205ull, 1,     167828ull,      1365238ull }, // 39 ld (nnnn),<ix,iy>
  {     144797ull,      1179730ull, 1,     144802ull,      1179763ull }, // 40 ld <bc,de,hl,sp>,nnnn
  {      73141ull,       593557ull, 1,      73146ull,       593590ull }, // 41 ld <ix,iy>,nnnn
  {     106316ull,       861298ull, 1,     106321ull,       861331ull }, // 42 ld a,<(bc),(de)>
  {     139116ull,      1135151ull, 1,     139121ull,      1135184ull }, // 43 ld <b,c,d,e,h,l,(hl),a>,nn
  {      73141ull,       593727ull, 1,      73146ull,       593760ull }, // 44 ld (<ix,iy>+1),nn
  {    1302907ull,     10489926ull, 1,    1302912ull,     10489959ull }, // 45 ld <b,c,d,e>,(<ix,iy>+1)
  {     647975ull,      5212332ull, 1,     647980ull,      5212365ull }, // 46 ld <h,l>,(<ix,iy>+1)
  {     311757ull,      2518052ull, 1,     311762ull,      2518085ull }, // 47 ld a,(<ix,iy>+1)
  {      73102ull,       590264ull, 1,      73107ull,       590297ull }, // 48 ld <ixh,ixl,iyh,iyl>,nn
  {   11166226ull,     90862646ull, 1,   11166231ull,     90862679ull }, // 49 ld <bcdehla>,<bcdehla>
  {   23031924ull,    186806071ull, 1,   23031929ull,    186806104ull }, // 50 ld <bcdexya>,<bcdexya>
  {     106224ull,       861206ull, 1,     106229ull,       861239ull }, // 51 ld a,(nnnn) / ld (nnnn),a
  {     106270ull,       861528ull, 1,     106275ull,       861561ull }, // 52 ldd<r> (1)
  {     106293ull,       862011ull, 1,     106298ull,       862044ull }, // 53 ldd<r> (2)
  {     106270ull,       861528ull, 1,     106275ull,       861561ull }, // 54 ldi<r> (1)
  {     106293ull,       862011ull, 1,     106298ull,       862044ull }, // 55 ldi<r> (2)
  {   32049776ull,    262717745ull, 1,   32049781ull,    262717778ull }, // 56 neg
  {   17373680ull,    141533239ull, 1,   17373685ull,    141533272ull }, // 57 <rrd,rld>
  {   14823845ull,    120813313ull, 1,   14823850ull,    120813346ull }, // 58 <rlca,rrca,rla,rra>
  {    1013379ull,      8186209ull, 1,    1013384ull,      8186242ull }, // 59 shf/rot (<ix,iy>+1)
  {   22598372ull,    183148570ull, 1,   22598377ull,    183148603ull }, // 60 shf/rot <b,c,d,e,h,l,(hl),a>
  {   22552296ull,    183598039ull, 1,   22552301ull,    183598072ull }, // 61 <set,res> n,<bcdehl(hl)a>
  {    1054025ull,      8570023ull, 1,    1054030ull,      8570056ull }, // 62 <set,res> n,(<ix,iy>+1)
  {    2975109ull,     23961558ull, 1,    2975114ull,     23961591ull }, // 63 ld (<ix,iy>+1),<b,c,d,e>
  {     647975ull,      5212332ull, 1,     647980ull,      5212365ull }, // 64 ld (<ix,iy>+1),<h,l>
  {     150832ull,      1216376ull, 1,     150837ull,      1216409ull }, // 65 ld (<ix,iy>+1),a
  {     233250ull,      1899702ull, 1,     233255ull,      1899735ull }, // 66 ld (<bc,de>),a
};
