// Generated by test/pc (zpc expect): per-group z80_step results of the
// reference core, each group run alone. Do not edit.
typedef struct { uint64_t steps, cycles; int pass; } zex_expect;
static const zex_expect zexdoc_expect[67] = {
  {  279550747ull,   2260470243ull, 1 }, //  0 <adc,sbc> hl,<bc,de,hl,sp>
  {  139195717ull,   1124958651ull, 1 }, //  1 add hl,<bc,de,hl,sp>
  {  139232069ull,   1125685691ull, 1 }, //  2 add ix,<bc,de,ix,sp>
  {  139232069ull,   1125685691ull, 1 }, //  3 add iy,<bc,de,iy,sp>
  {   70532174ull,    574692437ull, 1 }, //  4 aluop a,nn
  { 2461064646ull,  20006915235ull, 1 }, //  5 aluop a,<b,c,d,e,h,l,(hl),a>
  { 1255945312ull,  10169844747ull, 1 }, //  6 aluop a,<ixh,ixl,iyh,iyl>
  {  637477420ull,   5122999153ull, 1 }, //  7 aluop a,(<ix,iy>+1)
  {    4955376ull,     40245705ull, 1 }, //  8 bit n,(<ix,iy>+1)
  {  158658904ull,   1290420306ull, 1 }, //  9 bit n,<b,c,d,e,h,l,(hl),a>
  {   31068010ull,    252185444ull, 1 }, // 10 cpd<r>
  {   31085433ull,    252551327ull, 1 }, // 11 cpi<r>
  {  136056626ull,   1108961370ull, 1 }, // 12 <daa,cpl,scf,ccf>
  {    7352143ull,     59892057ull, 1 }, // 13 <inc,dec> a
  {    7352143ull,     59892057ull, 1 }, // 14 <inc,dec> b
  {    3793624ull,     30695186ull, 1 }, // 15 <inc,dec> bc
  {    7352143ull,     59892057ull, 1 }, // 16 <inc,dec> c
  {    7352143ull,     59892057ull, 1 }, // 17 <inc,dec> d
  {    3793624ull,     30695186ull, 1 }, // 18 <inc,dec> de
  {    7352143ull,     59892057ull, 1 }, // 19 <inc,dec> e
  {    7352143ull,     59892057ull, 1 }, // 20 <inc,dec> h
  {    3793624ull,     30695186ull, 1 }, // 21 <inc,dec> hl
  {    3795416ull,     30731026ull, 1 }, // 22 <inc,dec> ix
  {    3795416ull,     30731026ull, 1 }, // 23 <inc,dec> iy
  {    7352143ull,     59892057ull, 1 }, // 24 <inc,dec> l
  {    7352143ull,     59917145ull, 1 }, // 25 <inc,dec> (hl)
  {    3793624ull,     30695186ull, 1 }, // 26 <inc,dec> sp
  {   15411539ull,    125034707ull, 1 }, // 27 <inc,dec> (<ix,iy>+1)
  {    7355727ull,     59963737ull, 1 }, // 28 <inc,dec> ixh
  {    7355727ull,     59963737ull, 1 }, // 29 <inc,dec> ixl
  {    7355727ull,     59963737ull, 1 }, // 30 <inc,dec> iyh
  {    7355727ull,     59963737ull, 1 }, // 31 <inc,dec> iyl
  {      73073ull,       593081ull, 1 }, // 32 ld <bc,de>,(nnnn)
  {      36245ull,       293157ull, 1 }, // 33 ld hl,(nnnn)
  {      36228ull,       293157ull, 1 }, // 34 ld sp,(nnnn)
  {      73141ull,       593761ull, 1 }, // 35 ld <ix,iy>,(nnnn)
  {     167691ull,      1363885ull, 1 }, // 36 ld (nnnn),<bc,de>
  {      36245ull,       293157ull, 1 }, // 37 ld (nnnn),hl
  {      36228ull,       293157ull, 1 }, // 38 ld (nnnn),sp
  {     167823ull,      1365205ull, 1 }, // 39 ld (nnnn),<ix,iy>
  {     144797ull,      1179730ull, 1 }, // 40 ld <bc,de,hl,sp>,nnnn
  {      73141ull,       593557ull, 1 }, // 41 ld <ix,iy>,nnnn
  {     106316ull,       861298ull, 1 }, // 42 ld a,<(bc),(de)>
  {     139116ull,      1135151ull, 1 }, // 43 ld <b,c,d,e,h,l,(hl),a>,nn
  {      73141ull,       593727ull, 1 }, // 44 ld (<ix,iy>+1),nn
  {    1302907ull,     10489926ull, 1 }, // 45 ld <b,c,d,e>,(<ix,iy>+1)
  {     647975ull,      5212332ull, 1 }, // 46 ld <h,l>,(<ix,iy>+1)
  {     311757ull,      2518052ull, 1 }, // 47 ld a,(<ix,iy>+1)
  {      73102ull,       590264ull, 1 }, // 48 ld <ixh,ixl,iyh,iyl>,nn
  {   11166226ull,     90862646ull, 1 }, // 49 ld <bcdehla>,<bcdehla>
  {   23031924ull,    186806071ull, 1 }, // 50 ld <bcdexya>,<bcdexya>
  {     106224ull,       861206ull, 1 }, // 51 ld a,(nnnn) / ld (nnnn),a
  {     106270ull,       861528ull, 1 }, // 52 ldd<r> (1)
  {     106293ull,       862011ull, 1 }, // 53 ldd<r> (2)
  {     106270ull,       861528ull, 1 }, // 54 ldi<r> (1)
  {     106293ull,       862011ull, 1 }, // 55 ldi<r> (2)
  {   32049776ull,    262717745ull, 1 }, // 56 neg
  {   17373680ull,    141533239ull, 1 }, // 57 <rrd,rld>
  {   14823845ull,    120813313ull, 1 }, // 58 <rlca,rrca,rla,rra>
  {    1013379ull,      8186209ull, 1 }, // 59 shf/rot (<ix,iy>+1)
  {   22598372ull,    183148570ull, 1 }, // 60 shf/rot <b,c,d,e,h,l,(hl),a>
  {   22552296ull,    183598039ull, 1 }, // 61 <set,res> n,<bcdehl(hl)a>
  {    1054025ull,      8570023ull, 1 }, // 62 <set,res> n,(<ix,iy>+1)
  {    2975109ull,     23961558ull, 1 }, // 63 ld (<ix,iy>+1),<b,c,d,e>
  {     647975ull,      5212332ull, 1 }, // 64 ld (<ix,iy>+1),<h,l>
  {     150832ull,      1216376ull, 1 }, // 65 ld (<ix,iy>+1),a
  {     233250ull,      1899702ull, 1 }, // 66 ld (<bc,de>),a
};
static const zex_expect zexall_expect[67] = {
  {  279550747ull,   2260470243ull, 1 }, //  0 <adc,sbc> hl,<bc,de,hl,sp>
  {  139195717ull,   1124958651ull, 1 }, //  1 add hl,<bc,de,hl,sp>
  {  139232069ull,   1125685691ull, 1 }, //  2 add ix,<bc,de,ix,sp>
  {  139232069ull,   1125685691ull, 1 }, //  3 add iy,<bc,de,iy,sp>
  {   70532174ull,    574692437ull, 1 }, //  4 aluop a,nn
  { 2461064646ull,  20006915235ull, 1 }, //  5 aluop a,<b,c,d,e,h,l,(hl),a>
  { 1255945312ull,  10169844747ull, 1 }, //  6 aluop a,<ixh,ixl,iyh,iyl>
  {  637477420ull,   5122999153ull, 1 }, //  7 aluop a,(<ix,iy>+1)
  {    4955376ull,     40245705ull, 1 }, //  8 bit n,(<ix,iy>+1)
  {  158658904ull,   1290420306ull, 1 }, //  9 bit n,<b,c,d,e,h,l,(hl),a>
  {   31068010ull,    252185444ull, 1 }, // 10 cpd<r>
  {   31085433ull,    252551327ull, 1 }, // 11 cpi<r>
  {  136056626ull,   1108961370ull, 1 }, // 12 <daa,cpl,scf,ccf>
  {    7352143ull,     59892057ull, 1 }, // 13 <inc,dec> a
  {    7352143ull,     59892057ull, 1 }, // 14 <inc,dec> b
  {    3793624ull,     30695186ull, 1 }, // 15 <inc,dec> bc
  {    7352143ull,     59892057ull, 1 }, // 16 <inc,dec> c
  {    7352143ull,     59892057ull, 1 }, // 17 <inc,dec> d
  {    3793624ull,     30695186ull, 1 }, // 18 <inc,dec> de
  {    7352143ull,     59892057ull, 1 }, // 19 <inc,dec> e
  {    7352143ull,     59892057ull, 1 }, // 20 <inc,dec> h
  {    3793624ull,     30695186ull, 1 }, // 21 <inc,dec> hl
  {    3795416ull,     30731026ull, 1 }, // 22 <inc,dec> ix
  {    3795416ull,     30731026ull, 1 }, // 23 <inc,dec> iy
  {    7352143ull,     59892057ull, 1 }, // 24 <inc,dec> l
  {    7352143ull,     59917145ull, 1 }, // 25 <inc,dec> (hl)
  {    3793624ull,     30695186ull, 1 }, // 26 <inc,dec> sp
  {   15411539ull,    125034707ull, 1 }, // 27 <inc,dec> (<ix,iy>+1)
  {    7355727ull,     59963737ull, 1 }, // 28 <inc,dec> ixh
  {    7355727ull,     59963737ull, 1 }, // 29 <inc,dec> ixl
  {    7355727ull,     59963737ull, 1 }, // 30 <inc,dec> iyh
  {    7355727ull,     59963737ull, 1 }, // 31 <inc,dec> iyl
  {      73073ull,       593081ull, 1 }, // 32 ld <bc,de>,(nnnn)
  {      36245ull,       293157ull, 1 }, // 33 ld hl,(nnnn)
  {      36228ull,       293157ull, 1 }, // 34 ld sp,(nnnn)
  {      73141ull,       593761ull, 1 }, // 35 ld <ix,iy>,(nnnn)
  {     167691ull,      1363885ull, 1 }, // 36 ld (nnnn),<bc,de>
  {      36245ull,       293157ull, 1 }, // 37 ld (nnnn),hl
  {      36228ull,       293157ull, 1 }, // 38 ld (nnnn),sp
  {     167823ull,      1365205ull, 1 }, // 39 ld (nnnn),<ix,iy>
  {     144797ull,      1179730ull, 1 }, // 40 ld <bc,de,hl,sp>,nnnn
  {      73141ull,       593557ull, 1 }, // 41 ld <ix,iy>,nnnn
  {     106316ull,       861298ull, 1 }, // 42 ld a,<(bc),(de)>
  {     139116ull,      1135151ull, 1 }, // 43 ld <b,c,d,e,h,l,(hl),a>,nn
  {      73141ull,       593727ull, 1 }, // 44 ld (<ix,iy>+1),nn
  {    1302907ull,     10489926ull, 1 }, // 45 ld <b,c,d,e>,(<ix,iy>+1)
  {     647975ull,      5212332ull, 1 }, // 46 ld <h,l>,(<ix,iy>+1)
  {     311757ull,      2518052ull, 1 }, // 47 ld a,(<ix,iy>+1)
  {      73102ull,       590264ull, 1 }, // 48 ld <ixh,ixl,iyh,iyl>,nn
  {   11166226ull,     90862646ull, 1 }, // 49 ld <bcdehla>,<bcdehla>
  {   23031924ull,    186806071ull, 1 }, // 50 ld <bcdexya>,<bcdexya>
  {     106224ull,       861206ull, 1 }, // 51 ld a,(nnnn) / ld (nnnn),a
  {     106270ull,       861528ull, 1 }, // 52 ldd<r> (1)
  {     106293ull,       862011ull, 1 }, // 53 ldd<r> (2)
  {     106270ull,       861528ull, 1 }, // 54 ldi<r> (1)
  {     106293ull,       862011ull, 1 }, // 55 ldi<r> (2)
  {   32049776ull,    262717745ull, 1 }, // 56 neg
  {   17373680ull,    141533239ull, 1 }, // 57 <rrd,rld>
  {   14823845ull,    120813313ull, 1 }, // 58 <rlca,rrca,rla,rra>
  {    1013379ull,      8186209ull, 1 }, // 59 shf/rot (<ix,iy>+1)
  {   22598372ull,    183148570ull, 1 }, // 60 shf/rot <b,c,d,e,h,l,(hl),a>
  {   22552296ull,    183598039ull, 1 }, // 61 <set,res> n,<bcdehl(hl)a>
  {    1054025ull,      8570023ull, 1 }, // 62 <set,res> n,(<ix,iy>+1)
  {    2975109ull,     23961558ull, 1 }, // 63 ld (<ix,iy>+1),<b,c,d,e>
  {     647975ull,      5212332ull, 1 }, // 64 ld (<ix,iy>+1),<h,l>
  {     150832ull,      1216376ull, 1 }, // 65 ld (<ix,iy>+1),a
  {     233250ull,      1899702ull, 1 }, // 66 ld (<bc,de>),a
};
