// PC driver for the portable harness code (zdiff.c, zex.c, zcore.c), built
// with the host compiler by test/pc/Makefile. Used to validate the harness
// quickly and to generate test/zex_expect.h, the per-group reference numbers
// the N64 testsuite checks against.
//
//   zpc diff <cases> [seed]          REF vs NEW, then every mutant must fail
//   zpc zex <file> [group] [run]     run one exerciser (group -1 = all)
//   zpc expect <zexdoc> <zexall>     print zex_expect.h (z80_step and z80_run, every group)
//   zpc replay <trace>...            mvs64 owner traces: REF and NEW clean, MUT1 caught
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "zdiff.h"
#include "zex.h"
#include "replay.h"

static uint8_t* slurp(const char* fn, size_t* len) {
  FILE* f = fopen(fn, "rb");
  if (!f) { perror(fn); exit(2); }
  fseek(f, 0, SEEK_END); long sz = ftell(f); rewind(f);
  uint8_t* b = malloc(sz > 0 ? sz : 1);
  *len = fread(b, 1, sz, f);
  fclose(f);
  return b;
}

static int replay_all(int n, char** fns) {
  const zcore* cores[] = { &REF_core, &NEW_core, &MUT1_core };
  int fails = 0;
  for (int i = 0; i < n; i++) {
    size_t len; const uint8_t* tr = slurp(fns[i], &len);
    for (int c = 0; c < 3; c++) {
      replay_result r = replay(cores[c], tr, len, c < 2 ? 4 : 0);
      int ok = c < 2 ? (r.ended && !r.bad) : (r.bad || !r.ended);
      printf(">>> %s replay %s on %s: %ld runs, %ld instr, %ld IN/OUT, %ld mismatches%s\n",
             ok ? "PASS" : "FAIL", fns[i], cores[c]->name, r.runs, r.steps, r.io, r.bad,
             r.ended ? "" : ", desync before END");
      fails += !ok;
    }
    free((void*)tr);
  }
  return fails != 0;
}

static int diff(long cases, uint64_t seed) {
  const zcore* mut[] = { &MUT1_core, &MUT2_core, &MUT3_core, &MUT4_core };
  zdiff_cfg cfg = { .cases = cases, .seed = seed, .max_report = 2 };
  long bad = zdiff(&REF_core, &NEW_core, &cfg);
  printf(">>> %s zdiff REF vs NEW: %ld cases, %ld mismatches\n", bad ? "FAIL" : "PASS", cases, bad);
  int fails = bad != 0;
  for (int i = 0; i < 4; i++) {
    cfg.max_report = 0;
    long m = zdiff(&REF_core, mut[i], &cfg);
    printf(">>> %s zdiff control REF vs %s: %ld mismatches (must be > 0)\n",
           m ? "PASS" : "FAIL", mut[i]->name, m);
    fails += m == 0;
  }
  return fails != 0;
}

static void expect(const char* name, const uint8_t* img, size_t len) {
  int n = zex_groups(img, len);
  printf("static const zex_expect %s_expect[%d] = {\n", name, n);
  for (int g = 0; g < n; g++) {
    zex_result r = zex_run(&REF_core, img, len, g, 0, 1);
    zex_result u = zex_run(&REF_core, img, len, g, 1, 1);
    printf("  { %10lluull, %12lluull, %d, %10lluull, %12lluull }, // %2d %s\n",
           (unsigned long long)r.steps, (unsigned long long)r.cycles,
           r.ok == 1 && !r.err && u.ok == 1 && !u.err, (unsigned long long)u.steps,
           (unsigned long long)u.cycles, g, zex_group_name(img, len, g));
    fflush(stdout);
  }
  printf("};\n");
}

int main(int argc, char** argv) {
  if (argc >= 3 && !strcmp(argv[1], "diff"))
    return diff(atol(argv[2]), argc > 3 ? strtoull(argv[3], 0, 0) : 1);
  if (argc >= 3 && !strcmp(argv[1], "zex")) {
    size_t len; const uint8_t* img = slurp(argv[2], &len);
    int g = argc > 3 ? atoi(argv[3]) : -1;
    zex_result r = zex_run(&REF_core, img, len, g, argc > 4 && !strcmp(argv[4], "run"), 0);
    printf("*** %d OK, %d ERROR, %d complete, %llu instructions, %llu cycles\n", r.ok, r.err,
           r.complete, (unsigned long long)r.steps, (unsigned long long)r.cycles);
    return r.err != 0;
  }
  if (argc >= 3 && !strcmp(argv[1], "replay")) return replay_all(argc - 2, argv + 2);
  if (argc >= 4 && !strcmp(argv[1], "expect")) {
    size_t l1, l2; const uint8_t* doc = slurp(argv[2], &l1); const uint8_t* all = slurp(argv[3], &l2);
    printf("// Generated by test/pc (zpc expect): per-group results of the reference\n"
           "// core, each group run alone, driven by z80_step and by z80_run (whose\n"
           "// stop points overshoot the final OUT differently). Do not edit.\n"
           "typedef struct {\n"
           "  uint64_t steps, cycles; int pass;\n"
           "  uint64_t run_steps, run_cycles;\n"
           "} zex_expect;\n");
    expect("zexdoc", doc, l1);
    expect("zexall", all, l2);
    return 0;
  }
  fprintf(stderr, "usage: see test/pc/main.c\n");
  return 2;
}
