#!/usr/bin/env python3
r"""Generate n64z80_tables.h from the reference core's tables.

Reads the `.cyc_00`, `.cyc_ed` and `.cyc_ddfd` initializers in
reference/z80.c and writes one assembler symbol per opcode, so the asm
handlers charge exactly the reference's base cycles (GAS symbols, not
#defines, because handler macros build the names: CYC00_\op):

    .set CYC00_7E, 7        # cyc_00[0x7E]
    .set CYCED_B0, 16       # cyc_ed[0xB0]
    .set CYCDD_21, 14       # cyc_ddfd[0x21]

plus N64Z80_SZ53P, the reference's sz53p flag table as a byte list.
Included by n64z80_asm.S only.

usage: gen_tables.py reference/z80.c > build/n64z80_tables.h
"""
import re
import sys

TABLES = (("cyc_00", "CYC00"), ("cyc_ed", "CYCED"), ("cyc_ddfd", "CYCDD"))


def table(src, name):
    m = re.search(r"\." + name + r"\s*=\s*\{(.*?)\}", src, re.S)
    if not m:
        sys.exit("gen_tables: no .%s table" % name)
    vals = [int(v, 0) for v in re.findall(r"0x[0-9a-fA-F]+|\d+", m.group(1))]
    if len(vals) != 256:
        sys.exit("gen_tables: .%s has %d entries, expected 256" % (name, len(vals)))
    return vals


def main():
    src = open(sys.argv[1]).read()
    out = ["// Generated by tools/gen_tables.py from reference/z80.c. Do not edit.",
           "#ifndef N64Z80_TABLES_H", "#define N64Z80_TABLES_H"]
    for name, prefix in TABLES:
        for op, v in enumerate(table(src, name)):
            out.append(".set %s_%02X, %d" % (prefix, op, v))
    out.append("#define N64Z80_SZ53P " + ",".join("0x%02x" % v for v in table(src, "sz53p")))
    out.append("#endif")
    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
